"""posts table

Revision ID: 620d649e60e9
Revises: 76b5ca33c972
Create Date: 2018-01-27 17:22:05.276660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620d649e60e9'
down_revision = '76b5ca33c972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_date'), 'post', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_date'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
